apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::237659997883:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::237659997883:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IFCT9S3VWUK7
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-30T16:41:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "795"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dacc3446-f403-4c79-a69e-cd19ccf28c47
